chat/urls.py
from django.urls import path
from .views import chats_view, chat_room_view, get_chat_id, get_chats

app_name = 'chat'

urlpatterns = [
    path('', chats_view, name='chats'),
    path('get-chats/', get_chats, name='get_chats'),
    path('<int:chat_id>/', chat_room_view, name='room'),
    path('get-chat-id/<int:user_id>/', get_chat_id, name='get_chat_id'),
]

feed/urls.py
from django.urls import path

from .views import bookmarks_feed, bookmark_view, create_post_list, like_unlike_post

app_name = 'feed'

urlpatterns = [
    path('', create_post_list, name='feed'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('bookmark/', bookmark_view, name="bookmark-view"), 
    path('bookmarks/', bookmarks_feed, name='bookmarks'),
]

pinkler/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import home_view, tmp_bookmarks_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('feed/', include('feed.urls')),
    path('chats/', include('chat.urls', namespace='chat')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('search/', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils import timezone
from users.models import PinklerUser

LIKE_CHOISE = [
    ('Like', 'Like'),
    ('Unlike', 'Unlike')
]

class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='feed', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(PinklerUser, blank=True, related_name='likes')
    bookmark = models.ManyToManyField(PinklerUser, blank=True, related_name='bookmarks')

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(PinklerUser, on_delete=models.CASCADE, related_name='feed')

    def __str__(self):
        return str(self.content)
    
    def number_of_likes(self):
        return self.liked.all().count()
    
    def number_of_comments(self):
        return self.comment_set.all().count()
    
    def created_just_now(self):
        return timezone.now() - self.created < timezone.timedelta(minutes=1)
    
    class Meta:
        ordering = ('-created', )
    

class Comment(models.Model):
    user = models.ForeignKey(PinklerUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    body = models.TextField(max_length=150)
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


class Like(models.Model):
    user = models.ForeignKey(PinklerUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOISE, max_length=8)
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post}-{self.value}"

feed/forms.py
from django import forms
from .models import Post, Comment

from django import forms

class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image')
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Напишите что-нибудь...',
                'id':'post-form-content'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control-file',
                'id': 'file-upload',
                'style': 'display: nine;'
            }),
        }

    def __init__(self, *args, **kwargs):
        super(PostModelForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = ''
        self.fields['image'].label = ''

class CommentModelForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={
            'placeholder': 'Написать комментарий...',
            'class': 'form-comment'
        })
    )
    
    class Meta:
        model = Comment
        fields = ('body', )

feed/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from users.models import PinklerUser
from .forms import CommentModelForm, PostModelForm
from .models import Post, Like


@login_required(login_url='/accounts/login/')
def create_post_list(request):
    query_set = Post.objects.prefetch_related("comments").all()
    # comment_list = [post.comments.all() for post in query_set]
    pinkler_user = PinklerUser.objects.get(username=request.user.username)
    post_form = PostModelForm()
    comment_form = CommentModelForm()

    if 'post_button' in request.POST:
        post_form = PostModelForm(request.POST, request.FILES)
        if post_form.is_valid():
            instance = post_form.save(commit=False)
            instance.author = pinkler_user
            instance.save()
            return redirect('feed:feed')
        
    if 'comment_button' in request.POST:
        comment_form = CommentModelForm(request.POST)
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.user = pinkler_user
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            comment_form = CommentModelForm()

            query_set = Post.objects.prefetch_related("comments").all()
            return redirect('feed:feed')


    context = {
        'query_set': query_set, 
        'pinkler_user': pinkler_user, 
        'post_form': post_form,
        'comment_form': comment_form,
    }

    return render(request, 'feed/feed.html', context)

@login_required(login_url='/accounts/login/')
def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        pinkler_user = PinklerUser.objects.get(username=user.username)

        like, created = Like.objects.get_or_create(user=pinkler_user, post_id=post_id)

        if created:
            like.value = 'Like'
            post_obj.liked.add(pinkler_user)
            liked = True
        else:
            if like.value == 'Like':
                like.value = 'Unlike'
                post_obj.liked.remove(pinkler_user)
                liked = False
            else:
                like.value = 'Like'
                post_obj.liked.add(pinkler_user)
                liked = True
            
        post_obj.save()
        like.save()

    return JsonResponse({
            'liked': liked,
            'number_of_likes': post_obj.liked.count(),
        })

@login_required(login_url='/accounts/login/')
def bookmark_view(request):
    post_id = request.POST.get('post_id')
    user = request.user

    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        pinkler_user = PinklerUser.objects.get(username=user.username)

        if pinkler_user in post_obj.bookmark.all():
            post_obj.bookmark.remove(pinkler_user)
            bookmarked = False
        else:
            post_obj.bookmark.add(pinkler_user)
            bookmarked = True
            
        post_obj.save()

    return JsonResponse({'bookmarked': bookmarked})

@login_required(login_url='/accounts/login/')
def bookmarks_feed(request):
    query_set = Post.objects.prefetch_related("comments").all()
    pinkler_user = PinklerUser.objects.get(username=request.user.username)
    comment_form = CommentModelForm()

    if 'comment_button' in request.POST:
        comment_form = CommentModelForm(request.POST)
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.user = pinkler_user
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            comment_form = CommentModelForm()

            query_set = Post.objects.prefetch_related("comments").all()
            return redirect('feed:bookmarks')


    context = {
        'query_set': query_set, 
        'pinkler_user': pinkler_user, 
        'comment_form': comment_form,
    }

    return render(request, 'bookmarks/bookmarks.html', context)

templates/feed/comments_list.html
{% for comm in post.comments.all %}
    <div class="comment">
        <div class="head-comment">
            <div class="profile-photo"><img src="{{ comm.user.avatar.url }}"></div>
            <h3>{{ comm.user }}</h3>
        </div>
        <div class='caption'>{{ comm.body }}</div>
    </div>
{% empty %}
    <p>Комментариев нет.</p>
{% endfor %}

templates/feed/create_post.html
<div class="create-post">
    <form action="" method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{post_form.content}}
        <div id="file-preview" class="preview" style="display: none; margin: 5px 0;">
            <button type="button" id="remove-file" class="dash">✖</button>
            <img id="preview-image" src="" alt="Предварительный просмотр" />
        </div>
        <div class="create-buttons">
            <input type="file" id="file-upload" name="image" style="display: none;" />
            <label for="file-upload" class="btn btn-primary">Выбрать файл</label>
            <div id="file-name" class="mt-2"></div>
            <div class="post-button">
                <button type="submit" class="btn btn-primary" name="post_button" style="height: 43.2px;">Опубликовать</button>
            </div>
        </div>
    </form>
</div>

templates/feed/feed.html
{% extends 'content_base.html' %}
{% load static %}

{% block title %}
    <title>Главная</title>
{% endblock %}

{% block chats %}
    <script>
        loadChats();
    </script>
{% endblock %}

{% block content %}
    <div class="feed">
        {% include 'feed/create_post.html' %}
        {% for obj in query_set %}
            {% include 'includes/post.html' with obj=obj %}
        {% endfor %}
    </div>
    <script src="{% static 'scripts/feed.js' %}"></script>
{% endblock %}

templates/feed/post.html
<div class="feed">
    <div class="head">
        <div class="user">
            {% if obj.author.avatar %}
                <div class="profile-photo">
                    <img src="{{obj.author.avatar.url}}">
                </div>

            {% else %}
            <div class="profile-photo">
                <img src="static/images/avatars/default_avatar.png">
            </div>
            {% endif %}
            <div class="info">
                <h3>{{ obj.author.username }}</h3>
            
                {% if obj.created_just_now %}
                    <p>{{ obj.author }} - только что</p>
                {% else %}
                    <p>{{ obj.author }} - {{ obj.created|timesince }} назад</p>
                {% endif %}
            </div>
        </div>
        <form class="bookmark-form" method="POST" data-url="{% url 'feed:bookmark-view' %}">
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{obj.id}}">
            <button type="submit" class="bookmark" style="background-color: var(--color-white)">
                <i class="uil uil-bookmark-full {% if user in obj.bookmark.all %} bookmarked {% endif %}"></i>
            </button>
        </form>
        
    </div>

    {% if obj.image %}
    <div class="photo">
        <img src="{{obj.image.url}}">
    </div>
    {% endif %}

    <div class="caption">
        <p>{{obj.content}}</p>
    </div>

    <div class="action-buttons">
        <div class="interaction-buttons">
            <form class="like-form" method="POST" data-url="{% url 'feed:like-post-view' %}">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{obj.id}}">
                <button type="submit" class="sth" style="background-color: rgba(0, 0, 0, 0);">
                    <i class="uil uil-heart {% if user in obj.liked.all %} liked {% endif %}"></i>
                </button>
                <span class="like-count">{{ obj.liked.count }}</span>
                <span><i class="uil uil-comment-dots" style="background-color: rgba(0, 0, 0, 0);"></i></span>
                <span class="comments-count">{{ obj.comments.count }}</span>
            </form>
        </div>
    </div>
    <div class="see-comments">
        <button class="cmt_btn ui button mb-5" style="font-family: 'Nunito', sans-serif;">Показать/спрятать комментарии</button>
        <div class="comment-box" style="display: none;">
            {% include 'feed/comments_list.html' with post=obj %}
        </div>
        <div class="comment">
            <form action="" method="POST" class="ui form">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{obj.id}}">
                {{comment_form}}
                <button class="btn btn-primary" name="comment_button">отправить</button>
            </form>
        </div>
    </div>
</div>