chat/urls.py
from django.urls import path
from .views import chats_view, chat_room_view, get_chat_id, get_chats

app_name = 'chat'

urlpatterns = [
    path('', chats_view, name='chats'),
    path('get-chats/', get_chats, name='get_chats'),
    path('<int:chat_id>/', chat_room_view, name='room'),
    path('get-chat-id/<int:user_id>/', get_chat_id, name='get_chat_id'),
]

feed/urls.py
from django.urls import path

from .views import bookmarks_feed, bookmark_view, create_post_list, like_unlike_post

app_name = 'feed'

urlpatterns = [
    path('', create_post_list, name='feed'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('bookmark/', bookmark_view, name="bookmark-view"), 
    path('bookmarks/', bookmarks_feed, name='bookmarks'),
]

pinkler/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import home_view, tmp_bookmarks_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('feed/', include('feed.urls')),
    path('chats/', include('chat.urls', namespace='chat')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('search/', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import PinklerUserAuthenticationView, PinklerUserRegistrationView, EmailConfirmationView, \
    PinklerUserPasswordResetView, PinklerUserPasswordResetConfirmView, PasswordResetCompleteView, update_avatar_view
from .views import save_theme_preference, get_theme_preference, profile_view

urlpatterns = [
    path('register/', PinklerUserRegistrationView.as_view(), name='register'),
    path('login/', PinklerUserAuthenticationView.as_view(), name='login'),
    path('confirm_email/<uuid:token>/', EmailConfirmationView.as_view(), name='confirm_email'),
    path('password_reset/', PinklerUserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', PinklerUserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('save-theme-preference/', save_theme_preference, name='save_theme_preference'),
    path('get-theme-preference/', get_theme_preference, name='get_theme_preference'),
    path('update-avatar/', update_avatar_view, name='update_avatar'),
    path('<str:username>/', profile_view, name='profile'),
]

users/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.conf import settings

class PinklerUser(AbstractUser):
    SEX_CHOICES = (
        ("Мужской", "М"),
        ("Женский", "Ж"),
    )

    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    phone_number = models.CharField(max_length=12, unique=True, blank=True, null=True)
    sex = models.CharField(max_length=7, choices=SEX_CHOICES, default="М")
    status = models.TextField(blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    avatar = models.ImageField(upload_to='users/avatars/', default='users/avatars/default_avatar.png', blank=True,
                               null=True)
    friends = models.ManyToManyField("self", blank=True)

    def __str__(self):
        return self.username

    def __repr__(self):
        return self.__str__()

    def add_friend(self, user):
        if user != self:
            self.friends.add(user)
            user.friends.add(self)

    def remove_friend(self, user):
        self.friends.remove(user)
        user.friends.remove(self)

    def is_friends_with(self, user):
        return self.friends.filter(id=user.id).exists()

class EmailConfirmationToken(models.Model):
    user = models.OneToOneField(PinklerUser, on_delete=models.CASCADE)
    token = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def is_valid(self):
        return timezone.now() - self.created_at < timezone.timedelta(minutes=15)

    def __str__(self):
        return f'EmailConfirmationToken(user={self.user}, token={self.token})'

    def __repr__(self):
        return f'EmailConfirmationToken(user={self.user}, token={self.token}, created_at={self.created_at})'

class UserThemePreference(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="theme_preference")
    theme = models.CharField(max_length=50, default="light")
    font_size = models.CharField(max_length=10, default="16px")
    primary_color = models.CharField(max_length=7, default="#000000")

    def __str__(self):
        return f"Theme preferences for {self.user.username}"

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm, SetPasswordForm

from .models import PinklerUser


class PinklerUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={
            'placeholder': 'Имя пользователя',
            'required': 'required',
            'autofocus': 'autofocus'
        })
    )

    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Пароль',
            'required': 'required'
        })
    )

    password2 = forms.CharField(
        label='Подтвердите пароль',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Подтвердите пароль',
            'required': 'required'
        })
    )

    email = forms.EmailField(
        label='Адрес электронной почты',
        widget=forms.EmailInput(attrs={
            'placeholder': 'Адрес электронной почты',
            'required': 'required'
        })
    )

    # TODO: Add an interface for changing data in the user profile page.
    """
    These fields are not needed during registration,
    but will be needed in the future.
    For now, I'll just leave it here.
    """

    # phone_number = forms.CharField(
    #     label='Номер телефона',
    #     widget=forms.TextInput(attrs={
    #         'placeholder': 'Номер телефона',
    #     })
    # )
    #
    # sex = forms.ChoiceField(
    #     label='Пол',
    #     choices=SEX_CHOICES,
    #     initial='М',
    #     widget=forms.Select(attrs={
    #         'required': 'required'
    #     })
    # )
    #
    # status = forms.CharField(
    #     label='Статус',
    #     widget=forms.Textarea(attrs={
    #         'placeholder': 'Введите свой статус',
    #         'rows': 3,
    #         'cols': 40,
    #         'required': 'false'
    #     }),
    #     required=False
    # )
    #
    # birthday = forms.DateField(
    #     label='Дата рождения',
    #     widget=forms.DateInput(attrs={
    #         'type': 'date',
    #         'required': 'false'
    #     }),
    #     required=False
    # )
    #
    # avatar = forms.ImageField(
    #     label='Аватар',
    #     required=False
    # )

    class Meta:
        model = PinklerUser
        fields = ('username', 'email', 'password1', 'password2')


class PinklerUserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={
            'placeholder': 'Имя пользователя',
            'required': 'required',
            'autofocus': 'autofocus',
        })
    )

    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Пароль',
            'required': 'required',
        })
    )

    class Meta:
        model = PinklerUser
        fields = ('username', 'password')


class PinklerUserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label='Адрес электронной почты',
        widget=forms.EmailInput(attrs={
            'placeholder': 'Ваш email',
            'required': 'required'
        })
    )


class PinklerUserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='Новый пароль',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Новый пароль',
            'required': 'required',
            'autofocus': 'autofocus'
        })
    )

    new_password2 = forms.CharField(
        label='Подтвердите новый пароль',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Подтвердите новый пароль',
            'required': 'required'
        })
    )

users/views.py
import json

from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import generic, View
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.contrib.auth import login, get_user_model
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from .forms import PinklerUserCreationForm, PinklerUserAuthenticationForm, PinklerUserPasswordResetForm
from .forms import PinklerUserSetPasswordForm
from .models import PinklerUser, EmailConfirmationToken, UserThemePreference
from friends.models import FriendshipRequest
from feed.models import Post
from feed.forms import CommentModelForm


class PinklerUserRegistrationView(generic.CreateView):
    form_class = PinklerUserCreationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('feed')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        token_instance = EmailConfirmationToken.objects.create(user=user)

        confirmation_url = self.request.build_absolute_uri(
            reverse('confirm_email', kwargs={'token': token_instance.token})
        )

        subject = 'Подтвердите регистрацию в Pinkler'
        content = (
            f'Здравствуйте!\n\n'
            f'Вы получили это письмо, так как зарегистрировались в нашей социальной сети Pinkler.\n\n'
            f'Для подтверждения вашего адреса электронной почты, пожалуйста, перейдите по следующей ссылке:\n{confirmation_url}\n'
            'Если вы не регистрировались в Pinkler, просто проигнорируйте это письмо.\n\n'
            'Спасибо,\n'
            'Команда Pinkler.'
        )

        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [user.email]

        try:
            send_mail(subject, content, from_email, recipient_list)
            print('Письмо успешно отправлено')
        except Exception as e:
            print(f'Ошибка при отправке письма {e}')

        return render(self.request, 'users/request_email_confirmation.html', {'user': user})


class EmailConfirmationView(View):
    def get(self, request, token):
        confirmation_token = get_object_or_404(EmailConfirmationToken, token=token)

        if not confirmation_token.is_valid():
            return render(request, 'users/token_invalid.html')

        user = confirmation_token.user
        user.is_active = True
        user.save()

        login(request, user)

        confirmation_token.delete()

        return render(request, 'users/email_confirmed.html', {'user': user})


class PinklerUserAuthenticationView(LoginView):
    form_class = PinklerUserAuthenticationForm
    template_name = 'users/authentication.html'
    success_url = reverse_lazy('feed')

    def form_valid(self, form):
        return super().form_valid(form)


class PinklerUserPasswordResetView(generic.View):
    template_name = 'users/password_reset.html'
    form_class = PinklerUserPasswordResetForm
    success_url = reverse_lazy('password_reset_done')

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            User = get_user_model()
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                return render(request, 'users/email_not_found.html')

            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            password_reset_url = request.build_absolute_uri(
                reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
            )

            subject = 'Сброс пароля для Pinkler'
            content = (
                f'Здравствуйте!\n\n'
                f'Вы получили это письмо, потому что мы получили запрос на сброс пароля для вашей учетной '
                f'записи в Pinkler.\n\n'
                f'Чтобы сбросить пароль, перейдите по следующей ссылке:\n{password_reset_url}\n'
                'Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо и '
                'ваш пароль останется неизменным.\n\n'
                'Спасибо,\n'
                'Команда Pinkler.'
            )
            from_email = settings.DEFAULT_FROM_EMAIL
            recipient_list = [email]

            try:
                send_mail(subject, content, from_email, recipient_list)
                print('Письмо успешно отправлено')
            except Exception as e:
                print(f'Ошибка при отправке письма: {e}')

            return render(request, 'users/password_reset_done.html')

        return render(request, self.template_name, {'form': form})


class PinklerUserPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = PinklerUserSetPasswordForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('password_reset_complete')


class PasswordResetCompleteView(TemplateView):
    template_name = 'users/password_reset_complete.html'


@login_required(login_url='/accounts/login/')
def profile_view(request, username):

    if 'comment_button' in request.POST:
        comment_form = CommentModelForm(request.POST)
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.user = request.user
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            comment_form = CommentModelForm()

            query_set = Post.objects.prefetch_related("comments").all()
            return redirect('profile', username)

    comment_form = CommentModelForm()
    profile_owner = PinklerUser.objects.get(username=username)
    owner_posts = Post.objects.filter(author=profile_owner).prefetch_related("comments")
    owner_friends = profile_owner.friends.all()
    self_friends = request.user.friends.all()
    self_requested = PinklerUser.objects.filter(
        id__in=FriendshipRequest.objects.filter(created_by=request.user,
                                                      status=FriendshipRequest.SENT).values_list('created_for',
                                                                                                flat=True)
    )
    
    context = {
        'profile_owner': profile_owner,
        'owner_posts': owner_posts,
        'owner_friends': owner_friends,
        'self_friends': self_friends,
        'self_requested': self_requested,
        'comment_form': comment_form
    }
    return render(request, 'profiles/profile.html', context)


@csrf_exempt
@login_required(login_url='/accounts/login/')
def update_avatar_view(request):
    if request.method == 'POST' and request.FILES.get('avatar'):
        user = request.user
        if user is None:
            return JsonResponse({'error': 'Пользователь не найден'}, status=404)

        user.avatar = request.FILES['avatar']
        user.save()
        print('avatar has been updated')
        return JsonResponse({
            'success': True,
            'new_avatar_url': user.avatar.url
        })
    return JsonResponse({'error': 'Неверный запрос'}, status=400)


@csrf_exempt
@login_required(login_url='/accounts/login/')
def save_theme_preference(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        theme = data.get('theme')
        font_size = data.get('font_size')
        primary_color = data.get('primary_color')

        user_theme, created = UserThemePreference.objects.get_or_create(user=request.user)
        user_theme.theme = theme
        user_theme.font_size = font_size
        user_theme.primary_color = primary_color
        user_theme.save()

        return JsonResponse({'status': 'success'})
    return JsonResponse({'status': 'error'}, status=400)


@login_required(login_url='/accounts/login/')
def get_theme_preference(request):
    user = request.user
    theme_preference = UserThemePreference.objects.get(user=user)
    return JsonResponse({
        'font_size': theme_preference.font_size,
        'primary_color': theme_preference.primary_color,
        'theme': theme_preference.theme,
    })

templates/users/auth_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="{% static 'images/icons/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/auth.css' %}">
        {% block title %}
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% block container-content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/users/authentication.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Вход</title>
{% endblock %}

{% block container-content %}
    <h2>Вход</h2>
    <form method="POST" action="{% url 'login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Войти">
    </form>
    <div class="auth-link">
        <p>Забыли пароль? <a href="{% url 'password_reset' %}">Восстановить</a></p>
        <p>Нет аккаунта? <a href="{% url 'register' %}">Регистрация</a></p>
    </div>
{% endblock %}

templates/users/email_confirmed.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Подтверждение электронной почты</title>
{% endblock %}

{% block container-content %}
    <h2>Почта подтверждена!</h2>
    <p>Благодарим за подтверждение электронной почты. Ваша регистрация завершена.</p>
    <div class="auth-link">
        <p><a href="{% url 'feed:feed' %}">Перейти на главную страницу</a></p>
    </div>
{% endblock %}

templates/users/email_not_found.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Сброс пароля</title>
{% endblock %}

{% block container-content %}
    <h2>Упс, что-то пошло не так!</h2>
    <p>К сожалению, указанного адреса электронной почты не существует в нашей базе данных.</p>
    <p>Пожалуйста, проверьте правильность введенного адреса или попробуйте снова.</p>
    <div class="auth-link">
        <p><a href="{% url 'password_reset' %}">Вернуться к сбросу пароля</a></p>
    </div>
{% endblock %}

templates/users/password_reset.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Сброс пароля</title>
{% endblock %}

{% block container-content %}
    <h2>Сброс пароля</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сбросить пароль">
    </form>
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Сброс пароля</title>
{% endblock %}

{% block container-content %}
    <h2>Пароль изменен успешно!</h2>
    <p>Ваш пароль был изменен. Теперь вы можете войти в свою учетную запись.</p>
    <div class="auth-link">
        <p><a href="{% url 'login' %}">Перейти на страницу входа</a></p>
    </div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Сброс пароля</title>
{% endblock %}

{% block container-content %}
    <h2>Сброс пароля</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Установить новый пароль">
    </form>
{% endblock %}

templates/users/password_reset_done.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Сброс пароля</title>
{% endblock %}

{% block container-content %}
    <h2>Запрос на сброс пароля!</h2>
    <p>Мы отправили вам письмо со ссылкой для сброса пароля. Проверьте свою почту!</p>
    <p>Если вы не получили письмо, проверьте папку "Спам" или попробуйте снова.</p>
{% endblock %}

templates/users/registration.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Регистрация</title>
{% endblock %}

{% block container-content %}
    <h2>Регистрация</h2>
    <form method="POST" action="{% url 'register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Зарегистрироваться">
    </form>
    <div class="auth-link">
        <p>Уже есть аккаунт? <a href="{% url 'login' %}">Войти</a></p>
    </div>
{% endblock %}

templates/users/request_email_confirmation.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Подтверждение электронной почты</title>
{% endblock %}

{% block container-content %}
    <h2>Благодарим за регистрацию, {{ user.username }}!</h2>
    <p>Пожалуйста, подтвердите вашу электронную почту, чтобы завершить регистрацию.</p>
    <p>На адрес {{ user.email }} отправлено письмо со ссылкой для подтверждения. Не забудьте проверить спам!</p>
{% endblock %}

templates/users/token_invalid.html
{% extends 'users/auth_base.html' %}

{% block title %}
    <title>Подтверждение электронной почты</title>
{% endblock %}

{% block container-content %}
    <h2>Упс, что-то пошло не так!</h2>
{% endblock %}